/* Firmware configuration file. */

#ifndef _CORE_CONFIG_H
#define _CORE_CONFIG_H

#include <info.h>

#define LANGUAGE    LANG_RU

// Spirits parameters.
#define ACTION_TIMEOUT_YELLOW   5500
#define ACTION_TIMEOUT_BLUE     4500
#define ACTION_TIMEOUT_RED      4500
#define ACTION_TIMEOUT_PLTLAMP  10000
#define ACTION_TIMEOUT_PLTCAM   10000

#define MAX_ACTIVITY_LVL    20
#define MAX_POSSESSIVILITY_LVL  (MAX_ACTIVITY_LVL / 2)

#define NUM_OF_QUICK_MOVE_PREPARE_DEGREES   3
#define ACTION_TIMEOUT_QUICK    500
#define QUICK_LAST_MOVE_TIMEOUT_MULTIPLIER  3

// FLASH lights parameters
#define FLASH_LIGHTING_DURATION 300
#define FLASH_RECHARGE_TIMEOUT  10000

#define PWR_COST_IDLE   1
#define PWR_COST_LAMP   1
#define PWR_COST_TV     1
#define PWR_COST_CEILING    3
#define PWR_COST_FLASH  3
#define PWR_KILL_DELAY  1000
#define PWR_OFF_TIME    7000

#define CLOCK_TICK_PERIOD   30000

#endif // _CORE_CONFIG_H